name = "tasknexus-frontend"
compatibility_date = "2024-08-20"
pages_build_output_dir = "build"

[env.production]
name = "tasknexus-frontend"

[env.production.vars]
REACT_APP_API_URL = "https://your-api-domain.railway.app/api"
REACT_APP_ENV = "production"
